erDiagram

        ActionType {
            BAN_USER BAN_USER
UNBAN_USER UNBAN_USER
BAN_BUSINESS BAN_BUSINESS
UNBAN_BUSINESS UNBAN_BUSINESS
REMOVE_REVIEW REMOVE_REVIEW
REMOVE_PRODUCT REMOVE_PRODUCT
        }
    


        AdminActionTargetType {
            USER USER
BUSINESS BUSINESS
REVIEW REVIEW
SERVICE SERVICE
        }
    


        Role {
            BUYER BUYER
BUSINESS BUSINESS
ADMIN ADMIN
        }
    
  "AdminAction" {
    String id "🗝️"
    ActionType action 
    String details "❓"
    String targetId 
    AdminActionTargetType targetType 
    }
  

  "Admin" {
    String id "🗝️"
    String name 
    String email 
    String password 
    Boolean banned 
    String profile_img "❓"
    DateTime created_at 
    DateTime updated_at 
    }
  

  "Buyer" {
    String id "🗝️"
    String name 
    String email 
    String password 
    String salt 
    Boolean banned 
    String profile_img "❓"
    DateTime created_at 
    DateTime updated_at 
    }
  

  "Business" {
    String id "🗝️"
    String name 
    String email 
    String password 
    String salt 
    String description "❓"
    String logo "❓"
    DateTime created_at 
    DateTime updated_at 
    }
  

  "Message" {
    String id "🗝️"
    String content 
    DateTime created_at 
    }
  

  "Review" {
    String id "🗝️"
    Int rating 
    String comment "❓"
    DateTime created_at 
    }
  

  "Order" {
    String id "🗝️"
    DateTime created_at 
    }
  

  "Service" {
    String id "🗝️"
    String name 
    String description "❓"
    Float price 
    Int stock 
    String image "❓"
    DateTime created_at 
    }
  

  "Session" {
    String id "🗝️"
    String sessionId 
    String role 
    DateTime expires_at 
    String targetId 
    Role targetType 
    }
  
    "AdminAction" o|--|| "ActionType" : "enum:action"
    "AdminAction" o|--|| "AdminActionTargetType" : "enum:targetType"
    "AdminAction" o|--|| "Admin" : "admin"
    "Admin" o{--}o "AdminAction" : "AdminAction"
    "Buyer" o{--}o "Order" : "orders"
    "Buyer" o{--}o "Review" : "reviews"
    "Buyer" o{--}o "Message" : "sentMessages"
    "Buyer" o{--}o "Message" : "receivedMessages"
    "Business" o{--}o "Service" : "Service"
    "Business" o{--}o "Order" : "Order"
    "Business" o{--}o "Review" : "Review"
    "Message" o|--|| "Buyer" : "sender"
    "Message" o|--|| "Buyer" : "receiver"
    "Review" o|--|| "Buyer" : "customer"
    "Review" o|--|| "Business" : "business"
    "Order" o|--|| "Buyer" : "customer"
    "Order" o|--|| "Business" : "business"
    "Order" o|--|| "Service" : "product"
    "Service" o|--|| "Business" : "business"
    "Service" o{--}o "Order" : "Order"
    "Session" o|--|| "Role" : "enum:targetType"
